local canDebug = getgenv().canDebug
local run = function(func) func() end
local cloneref = cloneref or function(obj) return obj end

local playersService = cloneref(game:GetService('Players'))
local replicatedStorage = cloneref(game:GetService('ReplicatedStorage'))
local inputService = cloneref(game:GetService('UserInputService'))

local lplr = playersService.LocalPlayer
local tumbahub = shared.tumbahub
local entitylib = tumbahub.Libraries.entity
local sessioninfo = tumbahub.Libraries.sessioninfo
local bedwars

local function notif(...)
	return tumbahub:CreateNotification(...)
end

if canDebug then
    run(function()
        local KnitInit, Knit
        repeat
            KnitInit, Knit = pcall(function() return debug.getupvalue(require(lplr.PlayerScripts.TS.knit).setup, 9) end)
            if KnitInit then break end
            task.wait()
        until KnitInit
        if not debug.getupvalue(Knit.Start, 1) then
            repeat task.wait() until debug.getupvalue(Knit.Start, 1)
        end
        local Flamework = require(replicatedStorage['rbxts_include']['node_modules']['@flamework'].core.out).Flamework
        local Client = require(replicatedStorage.TS.remotes).default.Client

        bedwars = setmetatable({
            Client = Client,
            CrateItemMeta = debug.getupvalue(Flamework.resolveDependency('client/controllers/global/reward-crate/crate-controller@CrateController').onStart, 3),
            Store = require(lplr.PlayerScripts.TS.ui.store).ClientStore
        }, {
            __index = function(self, ind)
                rawset(self, ind, Knit.Controllers[ind])
                return rawget(self, ind)
            end
        })

        sessioninfo:AddItem('Kills')
        sessioninfo:AddItem('Beds')
        sessioninfo:AddItem('Wins')
        sessioninfo:AddItem('Games')

        tumbahub:Clean(function()
            table.clear(bedwars)
        end)
    end)
end

for i, v in tumbahub.Modules do
	if v.Category == 'Combat' or v.Category == 'Minigames' then
		tumbahub:Remove(i)
	end
end

run(function()
	local Sprint
	local old
	
	Sprint = tumbahub.Categories.Combat:CreateModule({
		Name = 'Sprint',
        Disabled = not canDebug,
		Function = function(callback)
			if callback then
				if inputService.TouchEnabled then pcall(function() lplr.PlayerGui.MobileUI['2'].Visible = false end) end
				old = bedwars.SprintController.stopSprinting
				bedwars.SprintController.stopSprinting = function(...)
					local call = old(...)
					bedwars.SprintController:startSprinting()
					return call
				end
				Sprint:Clean(entitylib.Events.LocalAdded:Connect(function() bedwars.SprintController:stopSprinting() end))
				bedwars.SprintController:stopSprinting()
			else
				if inputService.TouchEnabled then pcall(function() lplr.PlayerGui.MobileUI['2'].Visible = true end) end
				bedwars.SprintController.stopSprinting = old
				bedwars.SprintController:stopSprinting()
			end
		end,
		Tooltip = 'Sets your sprinting to true.'
	})
end)
	
run(function()
	local AutoGamble
	
	AutoGamble = tumbahub.Categories.Minigames:CreateModule({
		Name = 'Auto Gamble',
        Disabled = not canDebug,
		Function = function(callback)
			if callback then
				AutoGamble:Clean(bedwars.Client:GetNamespace('RewardCrate'):Get('CrateOpened'):Connect(function(data)
					if data.openingPlayer == lplr then
						local tab = bedwars.CrateItemMeta[data.reward.itemType] or {displayName = data.reward.itemType or 'unknown'}
						notif('AutoGamble', 'Won '..tab.displayName, 5)
					end
				end))
	
				repeat
					if not bedwars.CrateAltarController.activeCrates[1] then
						for _, v in bedwars.Store:getState().Consumable.inventory do
							if v.consumable:find('crate') then
								bedwars.CrateAltarController:pickCrate(v.consumable, 1)
								task.wait(1.2)
								if bedwars.CrateAltarController.activeCrates[1] and bedwars.CrateAltarController.activeCrates[1][2] then
									bedwars.Client:GetNamespace('RewardCrate'):Get('OpenRewardCrate'):SendToServer({
										crateId = bedwars.CrateAltarController.activeCrates[1][2].attributes.crateId
									})
								end
								break
							end
						end
					end
					task.wait(1)
				until not AutoGamble.Enabled
			end
		end,
		Tooltip = 'Automatically opens lucky crates, piston inspired!'
	})
end)
	